# Generated by Django 4.2.4 on 2024-06-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('serve', models.IntegerField(default=0)),
                ('Calories', models.IntegerField(default=0)),
                ('ingridients', models.CharField(blank=True, max_length=80, null=True)),
                ('type', models.CharField(blank=True, choices=[('Dishes', 'Dishes'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], max_length=20, null=True)),
                ('time', models.CharField(blank=True, choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=20, null=True)),
            ],
        ),
    ]
