# Generated by Django 4.2.4 on 2024-06-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('island', '0002_plat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
