# Generated by Django 4.2.4 on 2024-06-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('island', '0004_remove_plat_image_plat_image1_plat_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
