# Generated by Django 4.2.4 on 2024-06-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('island', '0007_plat_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=3000, null=True)),
                ('email', models.CharField(blank=True, max_length=3000, null=True)),
                ('time', models.TimeField(blank=True, max_length=20, null=True)),
                ('serve', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
