# Generated by Django 4.2.4 on 2024-06-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('island', '0008_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
    ]
